name: M-Web/D-web build size report commit

on: 
  pull_request:
     types:
      - closed
     branches:    
      - 'tip-buildsize-log'

env:
    NPM_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
    checkLabels-n-create-matrix:
      runs-on: ubuntu-latest
      if: ${{ github.event.pull_request.merged == true }}
      env:
        BOT_AUTH_TOKEN: ${{ secrets.BOT_AUTH_TOKEN }}
      
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - id: set-matrix
        run: |
          npm i
          node ./scripts/createMatrix.js
          echo $(cat matrix.txt)
          matrix=$(cat matrix.txt)

          # echo "this is formatted json"
          echo $matrix | jq .

          echo "::set-output name=matrix::$matrix"

    create-masterBuild-file:
        needs: [checkLabels-n-create-matrix]
        runs-on: ubuntu-latest
        timeout-minutes: 60
        strategy:
          matrix: ${{fromJSON(needs.checkLabels-n-create-matrix.outputs.matrix)}} #["portal-dweb", "portal-mweb"]

        steps:
            - name: setup Checkout
              if: ${{ success() }}
              uses: actions/checkout@v2
            
            - name: Setup node using 14.18.1
              if: ${{ success() }}
              uses: actions/setup-node@v1
              with:
                  node-version: 14.18.1

            - name: node version
              run: node -v

            - name: npm version
              run: npm -v

            - name: Fetch branches
              if: ${{ success() }}   
              run: git fetch --prune --unshallow

            - name: Creating env 'packagePath' and assigning a value to it
              if: ${{ success() }}
              run: |
                echo "packagePath=${{ matrix.label }}" >> $GITHUB_ENV

            - name: create .npmrc file
              if: ${{ success() }}
              run: |
                if [ ${{matrix.label}} = "portal-dweb" ]
                then
                  echo "creating npmrc for dweb"
                  make create-npmrc-dweb
                else
                  echo "creating npmrc for mweb"
                  make create-npmrc-mweb
                fi

            - name: install dependencies
              if: ${{ success() }}
              working-directory: ./packages/${{env.packagePath}}/
              run: |
                  node -v
                  npm ci

            - name: Create build and masterBuildSize.txt file
              if: ${{ success() }}
              working-directory: "./packages/${{env.packagePath}}/"
              run: |
                  npm run compile
                  du -hc ./build/* > ${{env.packagePath}}-buildSize.txt 

            - name: Upload code folder size
              if: ${{ success() }}
              uses: actions/upload-artifact@v3
              with:
                name: ${{env.packagePath}}.txt
                path: packages/${{env.packagePath}}/${{env.packagePath}}-buildSize.txt

    commitFile:
      runs-on: ubuntu-latest
      needs: [create-masterBuild-file]
      steps:    
        - name: setup checkout
          uses: actions/checkout@v2

        - name: Setting up github ssh
          uses: webfactory/ssh-agent@v0.4.1
          with:
              ssh-private-key: ${{ secrets.GHA_DEPLOY_KEY }}

        - name: Download d-web artifacts (build size stats file)
          if: ${{ success() && contains(github.event.pull_request.labels.*.name, 'portal-dweb') }}
          uses: actions/download-artifact@v3
          with:
            name: portal-dweb.txt

        - name: move portal-dweb.txt to the stats
          if: ${{ success() && contains(github.event.pull_request.labels.*.name, 'portal-dweb') }}
          run: mv portal-dweb-buildSize.txt stats/portal-dweb/masterBuildSize.txt

        - name: Download m-web artifacts (build size stats file)
          if: ${{ success() }}
          uses: actions/download-artifact@v3
          with:
            name: portal-mweb.txt

        - name: move portal-mweb.txt to the stats
          if: ${{ success() }}
          run: mv portal-mweb-buildSize.txt stats/portal-mweb/masterBuildSize.txt

        - name: git status
          working-directory: stats
          run : git status

        - name: Push to git
          run: |
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git remote set-url origin "git@github.com:${{ github.repository }}"
            git fetch
            echo `git add . && git commit -m "feat: update masterBuild.txt file" --no-verify && git push origin $GITHUB_BASE_REF`
            # EOF