name: add label

on:
  push:
    branches: [ main-silent ]
  
  pull_request:
    branches: [ main ]

jobs:
  add-label:
    runs-on: ubuntu-latest
    env:
      super_secret: ${{secrets.TOKEN}}
      message: "Hello, It's my first comment with Github action !"
    environment: production
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm i
    - run: echo $message
    - run: node addLabel.js

  second-step:
    needs: [ add-label ]
    runs-on: ubuntu-latest
    env:
      super_secret: ${{secrets.TOKEN}}
      message: "Hello, It's my first second-step!"
    environment: production
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm i
    - run: |
        value=${{node jsENV.js}}
        echo $value
    - run: echo $message
  
  