name: Build size custom

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  push:
    branches: [ nodeRead]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: echo "npm test"
    - run: mkdir -p artifact
    - run: du -hc ./build > artifact/current.txt
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: upload artifact
    # A file, directory or wildcard pattern that describes what to upload
        path: artifact
        if-no-files-found: error
        retention-days: 1 # optional

  # base branch
  build-base:
    name: Build base
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2

    - name: Display structure of downloaded files
      run: ls -R


  compare:
    runs-on: ubuntu-latest
    needs: [build-base, build]
    strategy:
      matrix:
        node-version: [ 12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: node readContent.js
