name: Build size comparsion

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      super_secret: ${{secrets.TOKEN}}
      message: "Hello, It's my first comment with Github action !"
    environment: production
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - run: npm i
    - run: node readContent.js
  