# This is a basic workflow to help you get started with Actions

name: CI, merge commit

on:
  pull_request:
    types:
      - closed
    branches:    
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: save current date
      run: |
        # do some operation that changes a file in the git repo
        du -hc ./build > masterBuild.txt
    
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    
    - name: commit
      run: |
        # Stage the file, commit and push
        git add masterBuild.txt
        git commit -m "updated buid size"
        git push origin mergeWork
    # Runs a set of commands using the runners shell
    
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    