name: on PR merge

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  pull_request:
    branches: [ main-2 ]
  push:
    branches: [ mergeWork ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo "step 1"
    - run: echo "npm test"
    - name: save current date
      run: |
        # do some operation that changes a file in the git repo
        date > time.txt

    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: commit
      run: |
        # Stage the file, commit and push
        git add time.txt
        git commit -m "new date commit"
    