# ref matrix : https://blog.slashgear.dev/how-to-dynamically-run-step-on-each-github-pr-label/
# ref shell  : https://www.journaldev.com/38145/if-else-in-shell-scripts#:~:text=Conditions%20in%20Shell%20Scripts&text=An%20if%2Delse%20statement%20allows,of%20statements%20using%20the%20result.

name: label loop

on:
  pull_request:
    #  types:
      # - closed
     branches:    
      - 'main'

jobs:
  checkLabels:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.labels.*.name[0]}}
    steps:
      - run: echo Check labels is not empty

  label-loop:
    needs: [checkLabels]
    environment: production
    runs-on: ubuntu-latest
    env:
        TOKEN: ${{ secrets.TESTINGTOKEN }}
        SSH: "${{ secrets.SSH }}"
  
    strategy:
      matrix:
        label: ["bug", "web"] #${{github.event.pull_request.labels.*.name}}
        # node-version: [ 12.x]
    
    steps:
        - uses: actions/checkout@v2
        # - uses: actions/setup-node@v1
          # with:
              # node-version: 14.11.0

        - name: check working with LABELS
          # if: contains(github.event.pull_request.labels.*.name, 'web')
          run: |         
            echo ${{contains(github.event.pull_request.labels.*.name, 'web')}}
            echo master--  ${{github.base_ref}} $GITHUB_BASE_REF
            echo current-- ${{github.head_ref}} $GITHUB_HEAD_REF
            echo labels-- ${{github.event.pull_request.labels}}
            echo matrix : ${{ matrix.label }}

        - name: IF - ELSE
          run: |
            if [ ${{matrix.label}} = "bug" ]
            then
              echo "bug label"
            else
              echo "web label"
            fi
            
