# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  push:
    branches: [ buildsize-actions ]
  pull_request:
    branches: [ buildsize-actions ]

jobs:
  build-base:
    name: Build base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}

    - name: Install dependencies
      run: echo "npm ci"
      env:
        NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

    - name: Build
      run: echo ${{ github.base_ref }}

