# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ bundlesize-actions ]
  pull_request:
    branches: [ main ]

jobs:

  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/upload-artifact@v2
      with:
        name: build-size-artifact
        path: ./buildSize.json
        if-no-files-found: error
        retention-days: 1

    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p artifact
    - run: echo hello > artifact/world.txt
    - uses: actions/upload-artifact@v2
  with:
    name: my-artifact
    path: artifact/world.txt

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run main:size
