# This is a basic workflow to help you get started with Actions

name: merge commit - build files size

on:
  pull_request:
    # types:
      # - closed
    branches:    
      - 'main'

jobs:
  commitFile:
  # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
        TOKEN: ${{ secrets.TESTINGTOKEN }}
        NODE_ENV: production
    steps:
    - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
      # uses: actions/setup-node@v2
      # with:
        # node-version: ${{ matrix.node-version }}
        # cache: 'npm'
    # - run: npm ci
    # - run: npm run build --if-present

    - name: save current build size
      # working-directory: ./src
      run: |
        # do some operation that changes a file in the git repo
        # du -hc ./log > masterBuild.txt
        echo "This is a log file" > log.txt

    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name amandhunna
        git config user.email amandhunna.dev@gmail.com
        git remote set-url origin "git@github.com:${{ github.repository }}"
        git fetch --all
    
    - name: commit
      run: |
        # Stage the file, commit and push
        git add .
        git commit -m "updated buid size"
        git push


    
