# This is a basic workflow to help you get started with Actions

name: merge commit - build files size

on:
  pull_request:
    # types:
      # - closed
    branches:    
      - 'main'

jobs:
  commitFile:
    environment: production
  # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # strategy:
      # matrix:
        # node-version: [ 12.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
        TOKEN: ${{ secrets.TESTINGTOKEN }}
        SSH: "${{ secrets.SSH }}"

    steps:
        - uses: actions/checkout@v2
        # - uses: actions/setup-node@v1
          # with:
              # node-version: 14.11.0
        - run: git fetch --prune --unshallow

        - name: Setting up
          uses: webfactory/ssh-agent@v0.4.1
          with:
              ssh-private-key: ${{ secrets.SSH  }}
        - name: Create masterBuild.txt file
          run: |
            echo "echo commit" > masterBuild.txt
        
        - name: check current branch name
          run: git rev-parse --abbrev-ref HEAD

        - name: check Head ref
          run: echo $GITHUB_HEAD_REF

        - name: check cut name
          run: echo $GITHUB_HEAD_REF | cut -d'/' -f 3

        - name: Push to git
          run: |
              git config user.email "amandhunna.dev@gmail.com"
              git config user.name "amandhunna"
              git remote set-url origin "git@github.com:${{ github.repository }}"
              # git fetch
              # git checkout -- .
              # git checkout --track origin/$(echo $GITHUB_HEAD_REF | cut -d'/' -f 3)
              echo `git add . && git commit -m "feat: masterBuild.txt file" --no-verify && git push`


    
