# This is a basic workflow to help you get started with Actions

name: merge commit - build files size

on:
  pull_request:
    #  types:
      # - closed
     branches:    
      - 'main'

jobs:
  commitFile:
    environment: production
    # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    # if: contains(github.event.pull_request.labels.*.name, 'web')
    runs-on: ubuntu-latest
    # strategy:
      # matrix:
        # node-version: [ 12.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
        TOKEN: ${{ secrets.TESTINGTOKEN }}
        SSH: "${{ secrets.SSH }}"
        packagePath: ${{contains(github.event.pull_request.labels.*.name, 'web')}}


    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: 14.11.0
        # - run: git fetch --prune --unshallow

        - run: |
            if ${packagePath} == true; then
              echo "path=dweb" >> $GITHUB_ENV
              echo "path set to the dweb
            else
              echo "path=mweb" >> $GITHUB_ENV
              echo "path set to the mweb"
            fi

        - name: Setting up
          uses: webfactory/ssh-agent@v0.4.1
          with:
              ssh-private-key: ${{ secrets.SSH  }}

        - name: Create masterBuild.txt file and GIT variables, check working with LABELS
          if: contains(github.event.pull_request.labels.*.name, 'web')
          run: |
            # rm -rf masterBuild.txt
            # echo "RSA is secrets section and .pub in ssh & gpg section..!." > masterBuild.txt
            
            echo master--  ${{github.base_ref}} $GITHUB_BASE_REF
            echo current-- ${{github.head_ref}} $GITHUB_HEAD_REF
            echo labels-- ${{github.event.pull_request.labels}}
            
            echo PR-- ${{github.ref_name}}
            echo Repo--${{github.repository}}
            echo Repo url-- ${{github.repositoryUrl}}
            echo isWeb Label-- ${{ github.event.label.name == 'web' }}
            echo Label name-- ${{ github.event.label.name}} # does not work

        - name: Creating and assigning value to a variable
          run: echo "-- $packagePath" # way to call self defined variables
        #     echo "i am"
        #     # isWeb = contains(github.event.pull_request.labels.*.name, 'web')
        #     # echo -- ${{isWeb}}
        #     # echo --d $isWeb

        - name: check current branch name
          run: git rev-parse --abbrev-ref HEAD

        - name: check Head ref
          run: echo $GITHUB_HEAD_REF

        - name: check cut name
          run: echo $GITHUB_HEAD_REF | cut -d'/' -f 3

        - name: run node file
          run: |
            npm i
            node console.js
            echo $github.event.pull_request.labels

        - name: Push to git
          if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
          run: |
              git config user.email "amandhunna.dev@gmail.com"
              git config user.name "amandhunna"
              git remote set-url origin "git@github.com:${{ github.repository }}"
              git fetch
              # git checkout -- .
              # git checkout --track origin/$(echo $GITHUB_BASE_REF | cut -d'/' -f 3)
              echo "current as head" $GITHUB_HEAD_REF
              echo "master as base" $GITHUB_BASE_REF
              echo "hello world 2" > commit.txt
              echo `git add . && git commit -m "feat: masterBuild.txt file" --no-verify && git push origin $GITHUB_BASE_REF`
